# Generated by Django 3.2.15 on 2023-01-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
