version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432
  
  backend:
    # image: vanadoo/foodgram_backend:latest
    # restart: always
    build:
      context: ../backend
      dockerfile: Dockerfile
    expose:
      - 8000
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: vanadoo/foodgram_frontend:latest
    # build:
    #   context: ../frontend
    #   dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
  db:
  result_build: