# Generated by Django 2.2.16 on 2022-12-07 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Название', max_length=200, unique=True, verbose_name='Название')),
                ('color', models.CharField(default='#FF0000', help_text='Цвет тэга в НЕХ-формате', max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6})$', 'Введите цвет в HEX-формате!')], verbose_name='Цвет тэга в НЕХ-формате')),
                ('slug', models.SlugField(help_text='Уникальный слаг', max_length=200, unique=True, verbose_name='Уникальный слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
    ]
